4.1)
SELECT ENAME,SAL 
FROM EMP
WHERE SAL BETWEEN 25600 AND 35500;

4.2)
SELECT ENAME,LOCATION,DNO
FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DNO
WHERE LOCATION IN('MUB','BNG','HYD');

SELECT ENAME,LOCATION,DNO
FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DNO
WHERE LOCATION='BNG' OR LOCATION='MUB' OR LOCATION='HYD';

4.3)
SELECT * FROM EMP ORDER BY DEPTNO,SAL DESC;

4.4)
CREATE TABLE MANAGER
AS SELECT EMPNO,ENAME,JOB,DEPTNO,SAL FROM EMP;

4.5)
SELECT ENAME
FROM EMP
WHERE MGRID=111;

4.6)
SELECT ENAME 
FROM EMP
WHERE ENAME LIKE('_AV%J');

4.7)
SELECT PRJ_NAME
FROM PROJ NATURAL JOIN DEPT 
WHERE DNAME='MARKETING';

4.8)
SELECT (INITCAP(ENAME)),LENGTH(ENAME),SUBSTR(ENAME,2,3) FROM EMP;

4.9)

4.10)
SELECT ENAME 
FROM EMP
WHERE MONTHS_BETWEEN(SYSDATE,DATE_JOIN)>48;

4.11)X
SELECT ENAME
FROM EMP
WHERE DATE_BIRTH LIKE('__-04%');

4.12)
SELECT JOB,SUM(SAL) 
FROM EMP
GROUP BY JOB;

4.13)
SELECT DNAME
FROM DEPT


