SELECT ENAME
FROM EMP
WHERE ENAME LIKE ('__H%') AND JOB='CLRK' AND SAL>27000;

-------------------------XX----------------------------
CREATE VIEW EMP_DEP 
AS SELECT DNAME,DEPT_BUDGET 
FROM DEPT AND SELECT ENAME FROM EMP
WHERE DEPT_BUDGET>700000;

SELECT ENAME,DNAME
FROM EMP
WHERE CITY=LOCATION;                 
